<head>
<link rel="stylesheet" type="text/css" href="general.css">
<link rel="icon" type="image/png" href="icon.ico">
</head>
<div id="wrapper">
  <div id="header">
    <div id="logo-pane">
        <div id="logo-content">
          <div id="image-border"><a href="home.php"><img src="Logo.jpg" width="100%"></a></div>
        </div>
      </div>
      <div id="title-pane">
        <div id="title-content">
          Timetable
        </div>
      </div>
    </div>

  <div id="footer">
    <div id="nav-bar">
      <div id="image-border"><a href="timetable.php"><img src="home.png" height="100%"></a></div>
      <div id="image-border"><a href="admin.php"><img src="admin.png" height="100%"></a></div>
      <div id="image-border"><a href="help.php"><img src="help.png" height="100%"></a></div>
      <div id="image-border"><a href="settings.php"><img src="setting.png" height="100%"></a></div>
    </div>
  </div>
  <div id="page-body">
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque porta quam nec felis cursus placerat. Ut risus enim, maximus vel dapibus eget, convallis quis mi. Proin eget ornare est. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Interdum et malesuada fames ac ante ipsum primis in faucibus. In velit ex, bibendum nec dui eu, molestie malesuada augue. Duis sed congue urna. Fusce mattis lobortis euismod. Nullam pretium sed velit at lobortis. Proin volutpat leo sit amet lacus viverra, id convallis ex venenatis. Phasellus eleifend lacus orci, non luctus libero viverra et. Donec hendrerit libero sed maximus ornare. Cras convallis ipsum risus, et feugiat magna lobortis in.
    <br>
    <br>Aenean non mi metus. Ut ultrices dignissim erat, quis tristique quam sagittis vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultricies ultrices risus vitae imperdiet. Aliquam aliquet ex aliquam velit maximus congue. Integer lobortis a ante in ultricies. Donec ac sem scelerisque, vulputate eros sit amet, auctor dolor. Nulla eu risus aliquet risus ultrices imperdiet imperdiet eu ex. Proin mattis eros nulla, in placerat urna auctor vitae. Nullam posuere tortor nisl, eu interdum dolor porta ac. Proin at dapibus dolor, imperdiet tempor libero. Morbi mollis pellentesque urna, sed cursus quam aliquet nec. Nunc mattis leo imperdiet, sagittis ex ut, dignissim augue. Suspendisse vulputate tortor at imperdiet bibendum.
    <br>
    <br>Vestibulum porta sapien id dui fermentum blandit. Nam non nulla lobortis, fringilla nulla vel, venenatis nulla. Sed urna justo, sollicitudin at augue id, placerat tristique turpis. Cras molestie iaculis justo quis cursus. Integer et eleifend quam, eget consequat nunc. Suspendisse consectetur eget lorem nec finibus. Pellentesque vel tincidunt ligula, vitae volutpat est. Praesent justo quam, pulvinar non quam eu, ultrices pulvinar ligula. Fusce quis magna sit amet justo lacinia maximus.
    <br>
    <br>Nullam eget dignissim libero. Nunc vel condimentum sem, ac malesuada lacus. Donec vel magna imperdiet, semper nibh eget, mollis mi. Ut ultricies aliquam felis et placerat. Vivamus ut sem ultricies leo faucibus efficitur ut eget est. Nunc posuere rhoncus odio in tempor. Pellentesque eget tellus sapien. Vivamus non eleifend diam. Nulla urna urna, pharetra eget lectus dapibus, vulputate blandit est. Suspendisse potenti. Vivamus egestas convallis est eget suscipit. Sed sem magna, luctus a quam id, efficitur volutpat lacus.
    <br>
    <br>Phasellus eleifend dui non dictum dignissim. Cras at nunc elit. Nullam interdum convallis erat, quis bibendum enim. Nullam ac fermentum elit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Duis placerat massa ac ex efficitur, condimentum interdum tortor fermentum. Phasellus tellus leo, ullamcorper eu vestibulum eu, vehicula nec diam. Duis volutpat dignissim odio, nec efficitur quam venenatis non. Nullam non aliquam urna. Quisque tristique eu sem et malesuada. Proin ante lacus, cursus id nibh sed, lobortis commodo leo.
    <br>
    <br>Fusce consectetur ac mauris at maximus. Duis semper mollis justo vitae efficitur. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus nec justo enim. Mauris aliquam congue pulvinar. Vivamus eget efficitur lacus, quis tincidunt nisl. Curabitur aliquam augue at tincidunt convallis. Suspendisse maximus, dui non feugiat viverra, felis leo blandit nulla, at fringilla arcu nulla sed nunc. Vivamus eleifend mi lorem, eget lacinia urna dignissim id. Sed non pretium elit. Donec semper leo nec nulla auctor euismod. Mauris leo nulla, aliquam quis risus id, varius tempus risus. Donec iaculis commodo erat, a luctus felis ornare vel.
    <br>
    <br>Nullam eget sodales ligula, sed molestie magna. Donec iaculis magna non dui consequat ullamcorper. Quisque laoreet suscipit aliquet. Quisque tincidunt neque in diam feugiat euismod. Donec semper tincidunt pellentesque. Morbi velit nisl, egestas quis luctus eget, sagittis sed nisi. Proin ex dolor, ultricies eget justo in, semper eleifend ex. Quisque dapibus sapien vel sapien tempor egestas. Aliquam vel orci vitae eros tempor tempor. In hac habitasse platea dictumst. Donec ac massa vehicula, accumsan ex eget, eleifend nisi. Vestibulum nec nibh quis leo varius tempus quis in orci. Suspendisse potenti.
    <br>
    <br>Suspendisse interdum libero enim, ac lacinia nibh ultricies ac. Proin ultrices, magna quis dictum varius, ante ante suscipit ante, at tincidunt augue felis vitae turpis. Nam leo augue, gravida posuere suscipit in, convallis sed felis. Phasellus eu diam fermentum, fermentum est quis, lobortis sapien. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed tempus enim nec porta lacinia. Phasellus condimentum varius sem a vulputate. Suspendisse placerat tellus metus. Nulla id enim sit amet dolor aliquet sollicitudin. Pellentesque vel vehicula orci, sed viverra lectus.
    <br>
    <br>Donec lacinia lorem ex, non mollis purus vestibulum in. Nunc quis mauris at ante sollicitudin interdum quis ac mi. Duis odio urna, porttitor sagittis erat sed, tristique aliquam nulla. Maecenas venenatis ante eu pulvinar egestas. Sed semper felis efficitur, scelerisque ex id, fringilla diam. Nullam vulputate enim quis venenatis mollis. Morbi at nunc posuere, rutrum lectus vel, accumsan purus. Aenean viverra sem tellus, ac hendrerit eros tempus ac. Phasellus sodales vulputate condimentum. Vivamus sit amet malesuada tortor, vitae suscipit metus. In consectetur malesuada lacus, ut tristique ligula.
    <br>
    <br>Aenean elit odio, facilisis sit amet porttitor sed, sagittis et nulla. Suspendisse augue leo, suscipit a finibus et, volutpat et nunc. Maecenas sodales, nisl vitae accumsan vestibulum, elit eros laoreet lectus, et vestibulum odio ipsum auctor sem. Nam odio turpis, viverra vitae posuere vel, maximus sit amet orci. Fusce congue lacus tortor, at commodo neque consequat at. Pellentesque a odio nisl. Ut libero ligula, facilisis et vestibulum et, pharetra vitae nisl. Donec luctus et lorem quis tristique. Pellentesque tempor ante ac metus euismod, nec consectetur orci cursus. Maecenas viverra, mauris nec elementum euismod, magna magna gravida lorem, vel convallis ipsum turpis non dui. Donec a erat at lectus maximus condimentum. Mauris molestie sed urna at suscipit. Nulla facilisi.
    <br>
    <br>Mauris at vehicula lectus, finibus hendrerit tellus. Curabitur nec euismod risus. Proin sit amet leo erat. Vestibulum aliquet, neque eget ornare hendrerit, metus risus consectetur mi, nec consectetur diam augue vitae metus. Praesent vulputate diam aliquam, tempus tellus non, tempor tortor. Donec gravida ultrices sapien ut placerat. Pellentesque molestie dui orci, sed pulvinar leo bibendum hendrerit. Nulla aliquet quam risus, vel fermentum diam mollis et. Praesent sed nulla vel massa vulputate iaculis eget quis dolor. Nullam volutpat varius neque at hendrerit. Aliquam semper lacus sit amet ipsum feugiat aliquet. Curabitur ac augue vitae sem accumsan tempus in non tellus. Donec aliquam dui eu dolor blandit, at pellentesque sem rutrum.
    <br>
    <br>Fusce volutpat urna consectetur, consequat est a, tincidunt dui. Quisque ante tellus, fringilla non enim sit amet, venenatis ultricies nunc. In malesuada, ipsum placerat posuere placerat, ex magna pulvinar felis, eget euismod metus tellus eu nunc. Etiam pretium porta neque. Fusce pharetra, augue id consectetur dignissim, dolor odio laoreet mi, finibus lobortis risus lectus id urna. Fusce eu eros at augue lobortis ornare at quis enim. Nulla id tellus ligula. Vivamus aliquet dui sed lorem porta porttitor.
    <br>
    <br>Suspendisse semper tincidunt arcu, eu sollicitudin mauris interdum a. Mauris posuere, nulla sit amet pretium lacinia, tellus metus molestie enim, in iaculis ex ligula vitae nunc. Cras blandit sollicitudin ipsum. Aenean vel tincidunt enim. Duis mauris massa, aliquet quis euismod nec, interdum quis quam. Sed dictum at risus in egestas. Fusce faucibus nunc sit amet vehicula venenatis. Nunc pretium tellus sed molestie pellentesque. Nam sodales auctor dui, at blandit eros euismod facilisis. In id arcu vitae ligula posuere molestie ut a nunc. Vivamus commodo urna odio, at lobortis eros mattis a. Duis gravida, lorem ac imperdiet fermentum, tortor neque consectetur diam, sit amet hendrerit purus felis at tellus. Aenean viverra nunc vitae dolor condimentum finibus. Maecenas at libero ac urna ornare vestibulum vitae non nisl. Aenean suscipit sagittis placerat.
    <br>
    <br>Curabitur finibus posuere finibus. Nullam sodales quis urna vitae ultricies. Integer gravida tortor urna, venenatis porta diam commodo in. Ut auctor neque nec molestie interdum. Vestibulum hendrerit mauris dolor, non volutpat mauris vehicula a. Aliquam mattis ut purus non venenatis. Mauris ultricies enim risus, eu eleifend lorem dignissim ac. Nunc viverra, massa vitae porta ornare, magna lorem ultrices nulla, ac tincidunt lectus urna vitae neque. Nunc rutrum ac nibh eu egestas. Nam in nulla id magna consectetur dapibus. Morbi sed ultricies lacus. Donec scelerisque mauris ac lectus posuere, facilisis semper est varius.
    <br>
    <br>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ac nisi nisl. Aliquam erat volutpat. Donec pharetra nisl ut eros iaculis congue. In id volutpat sapien. Donec quis posuere arcu. Cras blandit augue eu facilisis elementum. In non enim venenatis, suscipit ipsum nec, iaculis lorem. Praesent fermentum enim quis convallis pharetra. Fusce eu tortor ac sem tristique tincidunt quis sed magna. Duis ultricies nunc urna, dictum varius erat lobortis a.
    <br>
    <br>Etiam convallis ultrices elit in varius. Nam et libero id velit pellentesque varius. Etiam lacinia lacus in felis rutrum, at interdum erat vulputate. Duis in fringilla elit. Nulla ac est eget nisl interdum semper. Pellentesque ultricies aliquet ante, id sodales ex molestie vel. Integer porta viverra libero, nec venenatis dui lacinia ac. Nulla pellentesque, neque congue auctor ullamcorper, justo lectus cursus sem, at euismod justo erat nec arcu.
    <br>
    <br>Nam ultricies augue eu elementum semper. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent sodales, nisl sit amet vulputate vulputate, massa est lacinia enim, id dignissim magna eros eget nisl. Aenean semper finibus lorem at venenatis. Quisque nibh quam, mattis in tempor in, aliquam eget purus. Nulla accumsan risus a rhoncus varius. Nullam aliquam ante mi, eu luctus lacus molestie a. Fusce id magna enim. In hac habitasse platea dictumst. Vestibulum ornare risus a tincidunt ornare. Pellentesque sagittis tempus felis, sed pellentesque massa ultrices sit amet. Curabitur sit amet hendrerit neque.
    <br>
    <br>Morbi mattis eu lacus eget elementum. Etiam consectetur vehicula velit, ut volutpat diam efficitur dignissim. Etiam ac arcu vitae mi rutrum vulputate. Nullam pharetra condimentum velit, in porta leo maximus vel. Mauris eleifend, orci eu iaculis rhoncus, sapien turpis tristique purus, non iaculis lectus lacus convallis felis. Pellentesque at ipsum vel tortor pharetra cursus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In et fermentum quam. Nulla risus justo, suscipit sed eros a, scelerisque eleifend ligula. Pellentesque viverra nibh id sapien efficitur, vitae tempus dolor tincidunt. Cras nec est tincidunt, feugiat nisi a, pretium est. Phasellus lacinia ullamcorper ante eget scelerisque.
    <br>
    <br>Morbi commodo dictum nisl eget feugiat. Sed ut vestibulum ipsum, vitae imperdiet augue. Sed at massa condimentum, dapibus est sed, finibus justo. Vivamus pharetra dignissim imperdiet. Pellentesque tempor mi dui, vel aliquam metus convallis sed. Proin elementum, nunc id pharetra elementum, risus mauris lacinia velit, id feugiat mauris lacus at massa. Mauris at odio nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
    <br>
    <br>Praesent pharetra lobortis urna non tincidunt. Fusce arcu libero, vulputate maximus ullamcorper eget, euismod et enim. Nullam bibendum enim neque. Donec maximus est libero, id lacinia eros vehicula vel. Mauris commodo tempus nulla, in volutpat nulla. Vestibulum quis venenatis mi. In risus justo, vulputate nec ultrices ac, pulvinar a lectus. Vestibulum ultrices ex eu mi lacinia dignissim. Aliquam placerat in risus at mattis. Duis et est ut tellus accumsan rhoncus. Nulla consequat turpis et diam suscipit dignissim. Proin sed venenatis lacus, in vehicula velit. Maecenas et lacinia arcu. Donec ac sem augue.
    <br><!-- This is for readability on a computer, don't get rid of it. -->
  </div>
</div>
